theme: jekyll-theme-leap-day
title: Android Project Proposal
show_downloads: true
titles_from_headings:
  enabled: false
author:
  name: "Jan Gevaert"
  href: "https://"github.com/jangevaert-design"
  